#! /usr/bin/env bash

source core.sh
source init.sh
source new.sh
source edit.sh
source micro.sh
source files.sh
source deploy.sh
source archive.sh
source list.sh

echo '                 _'
echo '  __ _ _ __ ___ (_)'
echo " / _\` | '_ \` _ \| | gemini"
echo '| (_| | | | | | | | capsule'
echo ' \__, |_| |_| |_|_| generator'
echo ' |___/'
echo
echo "gmi -- version $__version"
echo "This program is free software."
echo -e "It is distributed AS IS with NO WARRANTY.\n"

entry="$1"

while :; do
  [[ $entry ]] || entry="$(list)"

  case $entry in
    init     ) init; break ;;
    new      ) shift; new "$1"; break ;;
    post     ) shift; post "$1"; break ;;
    index    ) edit_index index; break ;;
    micro    ) edit_index micro; break ;;
    archindex) edit_index archive ;;
    archived ) list_archived; break ;;
    "auto archive") confirm && auto_archive; break ;;
    deploy   ) deploy; break ;;
    quit     ) break
  esac

  echo "$entry"

  [[ $entry ]] && {
    title="$(get_title "$entry")"
    __err M "${entry#$src*}"
    __err M "$title"
    printf ":: [e]dit [r]ename [a]rchive [d]elete: "
    read -r r
    case $r in
      a) confirm "archive?" && archive "$entry" ;;
      d) confirm "delete?" && delete "$entry" ;;
      e) edit "$entry" ;;
      r) retitle_usr "$entry" ;;
      *) list
    esac
  }
  unset entry title r
done
