.TH GMI 1 0.6.2 Linux "User Manuals"
.SH NAME
\fB\fCgmi\fR \- Gemini Capsule Generator
.SH SYNOPSIS
.B gmi
[\fIOPTION\fR]
.SH DESCRIPTION
.PP
\fBGmi\fR is a Gemini Capsule Generator.
.PP

.SH OPTIONS
.TP

.SH AUTHOR
Written by Stéphane Meyer (Teegre).
.SH "REPORTING BUGS"
https://gitlab.com/teegre/gmi/issues
.SH LICENSE
License GPL.
.br
This is free software provided \fBAS IS\fR with \fBNO WARRANTY\fR. Feel free to change and redistribute.
