.TH GMI 1 0.7.1 Linux "User Manuals"
.SH NAME
\fB\fCgmi\fR \- Gemini Capsule Generator\.
.SH "SYNOPSIS"
.B gmi
<\fIOPTION\fR> [\fIVALUE\fR]
.SH "DESCRIPTION"
.PP
\fBGmi\fR is a Gemini capsule generator to easily manage articles, microblog posts and rss feed from the terminal\.
.SH "OPTIONS"
\fBinit\fR
  Create initial capsule directory structure and main files\.
.PP
\fBnew\fR [title]
  Create a new article\.
.PP
\fBpost\fR [msg]
  Add a new microblog entry\.
.br
  Invoked without argument, open default editor (set in EDITOR environment variable)\. When done, deploy to server\.
.PP
\fBpush\fR
  Deploy capsule on server\.
.PP
\fBpushm\fR
  Copy micro\.gmi file on server\.
.PP
\fBlist\fR
  Display list of already published articles (date title)\. When selected, other options are made available:
.IP "" 4
.nf

\fBedit\fR
  Open article in the editor set in the EDITOR environment variable\. If not set, **gmi** uses nano\.
  If any change is made to the title, it is updated in the main index\.gmi file\.

\fBrename\fR
  Change article\'s title in both article and main index\.gmi file\.

\fBdelete\fR
  Remove article\.

\fBarchive\fR
  Move article to archive directory and add a link to corresponding index\.gmi files\.
.
.fi
.
.IP "" 0
.
.P
\fBlista\fR
  Display archived article list\.
.br
  Selected article can be edited\.

\fBidx\fR
  Open main index\.gmi file for editing\.

\fBidxm\fR
  Open micro\.gmi file for editing\.

\fBidxa\fR
  Open archive main index\.gmi for editing\.

\fBarchive\fR
  Archive articles older than 1 year\.

\fBbackup\fR
  Create a backup copy of capsule\.

\fBrestore\fR
  Restore a previous backup copy\.
.SH "CONFIGURATION"
\fBGmi\fR reads its configuration in \fB$HOME/\.config/gmi/\fR
.
.P
As as starting point, an empty configuration file can be found at \fB/etc/gmi/config\fR
.
.SS "PARAMETERS"
\fBsource_dir\fR
  Capsule source directory\. Defaults to \fB~/\.gmi/src/\fR\.

\fBbackup_dir\fR
  Backup directory\. Defaults to \fB~/\.gmi/bak/\fR\.

\fBdate_format_article\fR
  Date format for articles\. Defaults to \fB%F\fR\.
  (Formatting is the same as \fBdate\fR command\.)

\fBdate_format_micro\fR
  Date format for microblog entries\. Defaults to \fB%F %T\fR\.
  (Formatting is the same as \fBdate\fR command\.)

\fBarticle_section_delimiter\fR
  Delimiter at the end of articles section\. Defaults to \fB\-\-\-\fR\.

\fByearly_archive_title\fR
  Title of yearly archive index file\. Defaults to \fBYear %y Archive\fR\.
  (\fB%y\fR expands to year)\.

\fBrss_title\fR

\fBrss_description\fR

\fBcapsule_url\fR

\fBserver_destination_dir\fR
  Capsule destination directory on server (i\.e: \fBuser@domain:/path\fR)\.

\fBssh_identity_file\fR
  Optional\.
  Path to identity file to use with ssh\.

\fBssh_port\fR
  Optional\.
  Port to use to establish ssh connection\.

.SS "CONFIGURATION TIP"
For convenience when deploying the capsule, you might want to disable password authentication for rsync on the server\.
To do so:

On the server, enter: \fBsudo visudo\fR

And add this line (replacing \fBuser\fR by your username): \fBuser ALL= NOPASSWD:/usr/bin/rsync\fR
.
.SH "AUTHOR"
Written by Stéphane Meyer (Teegre)\.
.
.SH "REPORTING BUGS"
\fIhttps://gitlab\.com/teegre/gmi/issues\fR
.
.SH "LICENSE"
License GPL\-v3
.
.P
This is free software provided \fBAS IS\fR with \fBNO WARRANTY\fR\.
.
.br
Feel free to change and redistribute\.
.
.P
For more info, see \fB/usr/share/licenses/gmi/LICENSE\fR\.
